In [1]:
import pandas as pd
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5]);

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int64')

In [9]:
x = torch.from_numpy(arr)

In [10]:
x

tensor([1, 2, 3, 4, 5])

In [11]:
type(x
)

torch.Tensor

In [13]:
arr2d = np.arange(0.0,12.0)

In [16]:
arr2d = arr2d.reshape(4,3)

In [18]:
arr2d


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

## x2 = torch.from_numpy(arr2d)

In [21]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[0] = 99


In [24]:
x

tensor([99,  2,  3,  4,  5])

In [25]:
my_arr = np.arange(0,10)

In [26]:
my_tensor = torch.tensor(my_arr)

In [27]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x3 = torch.Tensor([1,2,3
             ])

In [32]:
x3.dtype

torch.float32

In [33]:
torch.empty(2,2)

tensor([[7.0065e-45, 2.5938e+00],
        [2.3694e-38, 2.0031e-40]])

In [34]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [36]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [38]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [39]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [40]:
my_tensor = torch.tensor([1,2,3
                         ])

In [41]:
my_tensor

tensor([1, 2, 3])

In [46]:
my_tensor = my_tensor.type(torch.int32
              )

In [47]:
my_tensor.dtype


torch.int32

In [48]:
torch.rand(4,3)

tensor([[0.3129, 0.3355, 0.7394],
        [0.9401, 0.6238, 0.2111],
        [0.0260, 0.8044, 0.5451],
        [0.6143, 0.2487, 0.2789]])

In [49]:
torch.randn(4,3)

tensor([[ 0.3128, -0.5604, -0.4618],
        [ 2.1834, -1.2136,  0.8714],
        [-0.5788,  1.1352,  0.0279],
        [ 0.6338, -1.6369, -0.7698]])

In [50]:
torch.randint(low=0,high=10,size=(5,5
                                 ))

tensor([[5, 5, 0, 9, 6],
        [9, 3, 8, 3, 2],
        [6, 6, 1, 5, 5],
        [6, 9, 9, 7, 8],
        [3, 3, 5, 3, 4]])

In [51]:
x = torch.zeros(2,5)

In [52]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [53]:
torch.rand_like(x)


tensor([[0.2786, 0.1589, 0.3540, 0.0875, 0.5588],
        [0.3374, 0.7473, 0.7852, 0.7105, 0.6599]])

In [62]:
x = torch.arange(6).reshape(3,2)

In [63]:
x[1,1]

tensor(3)

In [64]:
x[:,1]

tensor([1, 3, 5])

In [65]:
x[:,1:
 ]

tensor([[1],
        [3],
        [5]])

In [66]:
x=torch.arange(10)

In [69]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [70]:
x


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [72]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
x = x.reshape(2,5
             )

In [74]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
x = torch.arange(10
                )

In [76]:
x.shape


torch.Size([10])

In [80]:
x = torch.arange(10)


In [81]:
x.shape


torch.Size([10])

In [82]:
x.view(2,-1
      )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [83]:
x.view(-1,5
      )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [90]:
a = torch.tensor([1.,2.,3.])

In [85]:
b = torch.tensor([4.,5.,6.
                 ])

In [86]:
b


tensor([4., 5., 6.])

In [87]:
a

tensor([1., 2., 3.])

In [88]:
a.mul_(b)


tensor([ 4., 10., 18.])

In [89]:
a


tensor([ 4., 10., 18.])

In [91]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [92]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [93]:
b = torch.tensor([[6,7],[9,7],[10,11]])

In [94]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [95]:
b

tensor([[ 6,  7],
        [ 9,  7],
        [10, 11]])

In [98]:
torch.mm(a,b)

tensor([[58, 58],
        [83, 83]])

In [101]:
x = torch.tensor([2.,3.,4.,5.])

In [103]:
x

tensor([2., 3., 4., 5.])

In [104]:
x.norm()

tensor(7.3485)

In [105]:
x.numel()

4

In [106]:
len(x)

4

In [107]:
len(a)

2

In [108]:
a.numel()

6